FROM openjdk:11-jre-slim-buster

ARG TINI="https://github.com/krallin/tini/releases/download/v0.19.0/tini"

ADD $TINI /sbin/tini
RUN chmod +x /sbin/tini

RUN addgroup --gid 10043 --system rootless \
 && adduser  --uid 10042 --system --ingroup rootless --no-create-home --gecos "" rootless
USER rootless

WORKDIR /opt/workspace
ENTRYPOINT ["/sbin/tini", "--", "java"]
CMD ["-version"]
