FROM openjdk:8-jdk-buster

ARG TINI="https://github.com/krallin/tini/releases/download/v0.19.0/tini"

RUN curl --location $TINI --output /sbin/tini \
 && chmod +x /sbin/tini

RUN addgroup --gid 10043 --system rootless \
 && adduser  --uid 10042 --system --ingroup rootless --no-create-home --gecos "" rootless
USER rootless

WORKDIR /opt/workspace

ENTRYPOINT ["/sbin/tini", "--", "java"]
CMD ["-version"]
