name: publish

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: docker hub login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: prepare buildx jre8
        uses: docker/setup-buildx-action@v1
        id: builder_jre8

      - name: prepare buildx jdk8
        uses: docker/setup-buildx-action@v1
        id: builder_jdk8

      - name: prepare buildx jre11
        uses: docker/setup-buildx-action@v1
        id: builder_jre11

      - name: prepare buildx jdk11
        uses: docker/setup-buildx-action@v1
        id: builder_jdk11

      - name: build jre8
        id: docker_build_jre8
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile-jre8
          builder: ${{ steps.builder_jre8.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/java:jre8

      - name: build jdk8
        id: docker_build_jdk8
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile-jdk8
          builder: ${{ steps.builder_jdk8.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/java:jdk8

      - name: build jre11
        id: docker_build_jre11
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile-jre11
          builder: ${{ steps.builder_jre11.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/java:jre11
            ${{ secrets.DOCKERHUB_USERNAME }}/java:latest

      - name: build jdk11
        id: docker_build_jdk11
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile-jdk11
          builder: ${{ steps.builder_jdk11.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/java:jdk11

      - name: image identifiers
        run: echo ${{ steps.docker_build.outputs.digest }}
